# Pobieramy oficjalny obraz Pythona
FROM python:3.10

# Ustawiamy katalog roboczy w kontenerze
WORKDIR /app

# Kopiujemy plik zależności i instalujemy pakiety
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Kopiujemy cały kod aplikacji do kontenera
COPY . .

# Otwieramy port na backendzie
EXPOSE 8000

# Uruchamiamy FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
