version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      # Użycie PostgreSQL zamiast wbudowanej bazy (H2)
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: start-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  primevue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: primevue-app
    ports:
      - "8081:80"
    environment:
      VITE_KEYCLOAK_URL: "http://keycloak:8080"
    depends_on:
      - keycloak

volumes:
  postgres_data:
